# Generated by Django 4.2.7 on 2023-12-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_price',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
